/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculora2;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class Calculadora extends javax.swing.JFrame {

    ScriptEngineManager sem = new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");

    public Calculadora() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
  @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/Calculator_30001.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_resultado = new javax.swing.JLabel();
        txt_operaciones = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_borrar = new javax.swing.JButton();
        btn_ultimo = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_multi = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setModalExclusionType(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 253, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_resultado.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txt_resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_resultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_resultado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, 70));

        txt_operaciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_operaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_operaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txt_operaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/darkmode_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 30, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText(".");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText(".");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 20, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_borrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_borrar.setText("C");
        btn_borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_borrar.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_borrar.setFocusPainted(false);
        btn_borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        btn_ultimo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_ultimo.setText("CE");
        btn_ultimo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ultimo.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_ultimo.setFocusPainted(false);
        btn_ultimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ultimo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ultimoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, 50));

        btn_mod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_mod.setText("%");
        btn_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_mod.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_mod.setFocusPainted(false);
        btn_mod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mod.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 50));

        btn_div.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_div.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_div.setText("÷");
        btn_div.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_div.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_div.setFocusPainted(false);
        btn_div.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_div.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });
        jPanel2.add(btn_div, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, 50));

        btn_multi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_multi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_multi.setText("X");
        btn_multi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_multi.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_multi.setFocusPainted(false);
        btn_multi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, 50));

        btn_resta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_resta.setText("-");
        btn_resta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_resta.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_resta.setFocusPainted(false);
        btn_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 50, 50));

        btn_suma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_suma.setText("+");
        btn_suma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_suma.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_suma.setFocusPainted(false);
        btn_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 50));

        btn_igual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn3.png"))); // NOI18N
        btn_igual.setText("=");
        btn_igual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_igual.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_igual.setFocusPainted(false);
        btn_igual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_igual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 50, 50));

        btn_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_7.setText("7");
        btn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_7.setFocusPainted(false);
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 50));

        btn_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_8.setText("8");
        btn_8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_8.setFocusPainted(false);
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 50));

        btn_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_9.setText("9");
        btn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_9.setFocusPainted(false);
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 50));

        btn_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_4.setText("4");
        btn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_4.setFocusPainted(false);
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 50));

        btn_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_5.setText("5");
        btn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_5.setFocusPainted(false);
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 50, 50));

        btn_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_6.setText("6");
        btn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_6.setFocusPainted(false);
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 50));

        btn_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_1.setText("1");
        btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_1.setFocusPainted(false);
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 50));

        btn_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_2.setText("2");
        btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_2.setFocusPainted(false);
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 50, 50));

        btn_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_3.setText("3");
        btn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_3.setFocusPainted(false);
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 50, 50));

        btn_0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_0.setText("0");
        btn_0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_0.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_0.setFocusPainted(false);
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 50));

        btn_punto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btn_punto.setText(".");
        btn_punto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_punto.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btn_punto.setFocusPainted(false);
        btn_punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1_preseend.png"))); // NOI18N
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 330, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
        txt_operaciones.setText("");
        txt_resultado.setText("");
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ultimoActionPerformed
        // TODO add your handling code here:
        String texto = txt_operaciones.getText().substring(0, txt_operaciones.getText().length() - 1);
        txt_operaciones.setText(texto);
        btn_igual.doClick();
    }//GEN-LAST:event_btn_ultimoActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:
        AddNumber("%");
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
        // TODO add your handling code here:
        AddNumber("/");
    }//GEN-LAST:event_btn_divActionPerformed

    private void btn_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiActionPerformed
        // TODO add your handling code here:
        AddNumber("*");
    }//GEN-LAST:event_btn_multiActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        AddNumber("-");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        AddNumber("+");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
        try {
            String resultado = se.eval(txt_operaciones.getText()).toString();
            txt_resultado.setText(resultado);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        AddNumber("7");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        AddNumber("8");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        AddNumber("9");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        AddNumber("4");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        AddNumber("5");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        AddNumber("6");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        AddNumber("1");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        AddNumber("2");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        AddNumber("3");
        btn_igual.doClick();

    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
        AddNumber("0");
        btn_igual.doClick();
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        AddNumber(".");
    }//GEN-LAST:event_btn_puntoActionPerformed
    boolean modooscuro = false;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!modooscuro) {
            

            CambiarBtn2(btn_ultimo);
            CambiarBtn2(btn_suma);
            CambiarBtn2(btn_resta);
            CambiarBtn2(btn_multi);
            CambiarBtn2(btn_div);
            CambiarBtn2(btn_borrar);
            CambiarBtn2(btn_mod);

            CambiarBnt(btn_1);
            CambiarBnt(btn_2);
            CambiarBnt(btn_3);
            CambiarBnt(btn_4);
            CambiarBnt(btn_5);
            CambiarBnt(btn_6);
            CambiarBnt(btn_7);
            CambiarBnt(btn_8);
            CambiarBnt(btn_9);
            CambiarBnt(btn_0);
            CambiarBnt(btn_punto);
            
            jPanel1.setBackground(new Color(33, 43, 65));
            jPanel2.setBackground(new Color(46, 57, 81));
            txt_operaciones.setForeground(Color.decode("#0db387"));
            txt_resultado.setForeground(Color.decode("#0db387"));

            jButton2.setIcon(new ImageIcon(getClass().getResource("/images/darkmode_2.png")));
            //Estilo de boton =
            btn_igual.setIcon(new ImageIcon(getClass().getResource("/images/btn_igual.png")));
            btn_igual.setRolloverIcon(new ImageIcon(getClass().getResource("/images/btn_presedar.png")));
            modooscuro = true;

        } else {
            jPanel1.setBackground(Color.decode("#f4fdfb"));
            jPanel2.setBackground(Color.white);
            txt_operaciones.setForeground(Color.decode("#373e47"));
            txt_resultado.setForeground(Color.decode("#373e47"));
            
            jButton2.setIcon(new ImageIcon(getClass().getResource("/images/darkmode_1.png")));
            //Estilo de boton =
            btn_igual.setIcon(new ImageIcon(getClass().getResource("/images/btn3.png")));
            btn_igual.setRolloverIcon(new ImageIcon(getClass().getResource("/images/boton1_preseend.png")));

            CambiarModBlanco(btn_0);
            CambiarModBlanco(btn_1);
            CambiarModBlanco(btn_2);
            CambiarModBlanco(btn_3);
            CambiarModBlanco(btn_4);
            CambiarModBlanco(btn_5);
            CambiarModBlanco(btn_6);
            CambiarModBlanco(btn_7);
            CambiarModBlanco(btn_8);
            CambiarModBlanco(btn_9);
            CambiarModBlanco(btn_punto);

            CambiarModBlacodar(btn_ultimo);
            CambiarModBlacodar(btn_borrar);
            CambiarModBlacodar(btn_suma);
            CambiarModBlacodar(btn_resta);
            CambiarModBlacodar(btn_multi);
            CambiarModBlacodar(btn_div);
            CambiarModBlacodar(btn_mod);

            modooscuro = false;
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked
    public void AddNumber(String digitos) {
        txt_operaciones.setText(txt_operaciones.getText() + digitos);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_multi;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton btn_ultimo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_operaciones;
    private javax.swing.JLabel txt_resultado;
    // End of variables declaration//GEN-END:variables
    public void CambiarBnt(JButton btn) {
        btn.setIcon(new ImageIcon(getClass().getResource("/images/btn_dar.png")));
        btn.setRolloverIcon(new ImageIcon(getClass().getResource("/images/btn_presedar.png")));
        btn.setPressedIcon(new ImageIcon(getClass().getResource("/images/btn_dar.png")));
        btn.setForeground(Color.decode("#96a8a0"));
    }

    public void CambiarBtn2(JButton btn2) {
        btn2.setIcon(new ImageIcon(getClass().getResource("/images/btn_presedar.png")));
        btn2.setRolloverIcon(new ImageIcon(getClass().getResource("/images/btn_presedar.png")));
        btn2.setPressedIcon(new ImageIcon(getClass().getResource("/images/btn_dar.png")));
        btn2.setForeground(Color.decode("#0db387"));
    }

    public void CambiarModBlanco(JButton btn3) {

        btn3.setIcon(new ImageIcon(getClass().getResource("/images/boton2.png")));
        btn3.setRolloverIcon(new ImageIcon(getClass().getResource("/images/boton1_preseend.png")));
        btn3.setPressedIcon(new ImageIcon(getClass().getResource("/images/boton1.png")));
        btn3.setForeground(Color.decode("#373e47"));
    }

    public void CambiarModBlacodar(JButton btn4) {
        btn4.setIcon(new ImageIcon(getClass().getResource("/images/boton1.png")));
        btn4.setRolloverIcon(new ImageIcon(getClass().getResource("/images/boton1_preseend.png")));
        btn4.setPressedIcon(new ImageIcon(getClass().getResource("/images/boton1.png")));
        btn4.setForeground(Color.decode("#373e47"));
    }

}
